export type Lang = "en" | "vi";

export interface Dictionary {
  meta: {
    title: string;
    description: string;
  };
  header: {
    logo: string;
    tagline: string;
  };
  input: {
    heading: string;
    subtitle: string;
    placeholder: string;
    generateBtn: string;
    hint: string;
  };
  recent: {
    heading: string;
    exportBtn: string;
    empty: string;
  };
  loading: {
    text: string;
  };
  lesson: {
    beginnerLabel: string;
    intermediateLabel: string;
    advanceLabel: string;
    generatedOn: string;
    totalWords: string;
    wordsSuffix: string;
  };
  article: {
    newTopic: string;
    fontSizeTitle: string;
    printTitle: string;
    footer: string;
    titlePrefix: string;
  };
  errorMessage: string;
}

const en: Dictionary = {
  meta: {
    title: "Simple Explain - Three-Level Learning Path",
    description:
      "Generate progressive explanations from beginner to advanced depth",
  },
  header: {
    logo: "Simple Explain",
    tagline: "From first principles to deep understanding",
  },
  input: {
    heading: "Choose a topic to break down",
    subtitle:
      "Get one structured lesson with beginner, intermediate, and advanced depth in a single response.",
    placeholder: "e.g., Inflation, Neural Networks, Stoicism...",
    generateBtn: "Generate Lesson",
    hint: "The app produces strict JSON and then renders each level as readable sections.",
  },
  recent: {
    heading: "Recent lessons",
    exportBtn: "EXPORT JSON",
    empty: "No lessons generated yet.",
  },
  loading: {
    text: "Building your three-level lesson...",
  },
  lesson: {
    beginnerLabel: "Beginner",
    intermediateLabel: "Intermediate",
    advanceLabel: "Advanced",
    generatedOn: "Generated",
    totalWords: "Total",
    wordsSuffix: "words",
  },
  article: {
    newTopic: "New topic",
    fontSizeTitle: "Adjust font size",
    printTitle: "Print lesson",
    footer: "Generated by Simple Explain",
    titlePrefix: "Learning Path:",
  },
  errorMessage: "Failed to generate the lesson. Please try again.",
};

const vi: Dictionary = {
  meta: {
    title: "Giải Thích Đơn Giản - Lộ Trình Học 3 Tầng",
    description:
      "Tạo bài giải thích tiến dần từ cơ bản đến nâng cao trong một lần",
  },
  header: {
    logo: "Giải Thích Đơn Giản",
    tagline: "Từ nền tảng đến hiểu sâu một cách có hệ thống",
  },
  input: {
    heading: "Chọn chủ đề bạn muốn hiểu rõ",
    subtitle:
      "Nhận một bài học có cấu trúc gồm 3 mức: beginner, intermediate và advance.",
    placeholder: "VD: Lạm phát, Mạng nơ-ron, Chủ nghĩa khắc kỷ...",
    generateBtn: "Tạo Bài Học",
    hint: "Ứng dụng tạo JSON nghiêm ngặt rồi hiển thị thành các phần dễ đọc.",
  },
  recent: {
    heading: "Bài học gần đây",
    exportBtn: "XUẤT JSON",
    empty: "Chưa có bài học nào.",
  },
  loading: {
    text: "Đang tạo bài học 3 mức độ...",
  },
  lesson: {
    beginnerLabel: "Cơ bản",
    intermediateLabel: "Trung cấp",
    advanceLabel: "Nâng cao",
    generatedOn: "Tạo lúc",
    totalWords: "Tổng",
    wordsSuffix: "từ",
  },
  article: {
    newTopic: "Chủ đề mới",
    fontSizeTitle: "Điều chỉnh cỡ chữ",
    printTitle: "In bài học",
    footer: "Được tạo bởi Giải Thích Đơn Giản",
    titlePrefix: "Lộ Trình Học:",
  },
  errorMessage: "Không thể tạo bài học. Vui lòng thử lại.",
};

const dictionaries: Record<Lang, Dictionary> = { en, vi };

export function getDictionary(lang: Lang): Dictionary {
  return dictionaries[lang] || dictionaries.en;
}

export const locales: Lang[] = ["en", "vi"];
